# Generated by Django 5.1.6 on 2025-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('temperatures', models.JSONField()),
                ('score_energetique', models.JSONField(default=dict)),
            ],
        ),
    ]
