# Generated by Django 5.1.6 on 2025-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='score_elec',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='departement',
            name='score_ixp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='departement',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
