# Generated by Django 5.1.6 on 2025-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_departement_score_elec_departement_score_ixp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='score_eolienne',
            field=models.FloatField(default=0),
        ),
    ]
